import type { Scenario, TransactionRequest } from '@/types'

export const isolatedScenarios: Scenario[] = [
  {
    id: 'S01_clean_normal',
    name: 'S01: Clean normal payment',
    description: 'No strong risk signals; baseline clean transaction.',
    suite: 'isolated',
    expected: {
      decision: 'ALLOW',
      scoreMin: 0,
      scoreMax: 0.39,
      allowExtraReasons: true,
    },
    category: 'ALLOW',
    payload: {
      transaction_id: 'tx-s01', user_id: 'user-001', amount: 49.99, currency: 'USD', country: 'US', ip_address: '203.0.113.10', device_id: 'device-001', merchant_id: 'merchant-001', merchant_category: 'retail', account_age_days: 365, is_international: false, timestamp: '2026-03-20T12:00:00Z',
    },
  },
  {
    id: 'S02_unusual_hour_only',
    name: 'S02: Small amount at unusual hour',
    description: 'Only unusual hour signal expected; should stay ALLOW.',
    suite: 'isolated',
    expected: {
      decision: 'ALLOW',
      scoreMin: 0,
      scoreMax: 0.45,
      mustIncludeReasons: ['unusual_hour'],
      allowExtraReasons: false,
    },
    category: 'ALLOW',
    payload: {
      transaction_id: 'tx-s02', user_id: 'user-002', amount: 35.0, currency: 'USD', country: 'US', ip_address: '203.0.113.11', device_id: 'device-002', merchant_id: 'merchant-002', merchant_category: 'retail', account_age_days: 400, is_international: false, timestamp: '2026-03-20T03:10:00Z', transaction_hour: 3,
    },
  },
  {
    id: 'S03_round_amount_only',
    name: 'S03: Round amount only',
    description: 'Round amount signal in isolation.',
    suite: 'isolated',
    expected: {
      decision: 'ALLOW',
      scoreMin: 0,
      scoreMax: 0.45,
      mustIncludeReasons: ['round_amount'],
      allowExtraReasons: false,
    },
    category: 'ALLOW',
    payload: {
      transaction_id: 'tx-s03', user_id: 'user-003', amount: 500.0, currency: 'USD', country: 'US', ip_address: '203.0.113.12', device_id: 'device-003', merchant_id: 'merchant-003', merchant_category: 'retail', account_age_days: 500, is_international: false, timestamp: '2026-03-20T12:20:00Z',
    },
  },
  {
    id: 'S04_international_only',
    name: 'S04: International only',
    description: 'Low-risk international transaction only.',
    suite: 'isolated',
    expected: {
      decision: 'ALLOW',
      scoreMin: 0,
      scoreMax: 0.45,
      mustIncludeReasons: ['international_transaction'],
      allowExtraReasons: false,
    },
    category: 'ALLOW',
    payload: {
      transaction_id: 'tx-s04', user_id: 'user-004', amount: 60.0, currency: 'USD', country: 'CA', ip_address: '203.0.113.13', device_id: 'device-004', merchant_id: 'merchant-004', merchant_category: 'retail', account_age_days: 450, is_international: true, timestamp: '2026-03-20T12:30:00Z',
    },
  },
  {
    id: 'S05_high_amount_only',
    name: 'S05: High amount only',
    description: 'High amount should push decision to REVIEW.',
    suite: 'isolated',
    expected: {
      decision: 'REVIEW',
      scoreMin: 0.4,
      scoreMax: 0.79,
      mustIncludeReasons: ['high_amount'],
      allowExtraReasons: false,
    },
    category: 'REVIEW',
    payload: {
      transaction_id: 'tx-s05', user_id: 'user-005', amount: 5000.5, currency: 'USD', country: 'US', ip_address: '203.0.113.14', device_id: 'device-005', merchant_id: 'merchant-005', merchant_category: 'retail', account_age_days: 365, is_international: false, timestamp: '2026-03-20T13:00:00Z',
    },
  },
  {
    id: 'S06_high_risk_country_only',
    name: 'S06: High-risk country only',
    description: 'High-risk country in isolation.',
    suite: 'isolated',
    expected: {
      decision: 'REVIEW',
      scoreMin: 0.4,
      scoreMax: 0.79,
      mustIncludeReasons: ['high_risk_country'],
      allowExtraReasons: false,
    },
    category: 'REVIEW',
    payload: {
      transaction_id: 'tx-s06', user_id: 'user-006', amount: 80.0, currency: 'USD', country: 'NG', ip_address: '203.0.113.15', device_id: 'device-006', merchant_id: 'merchant-006', merchant_category: 'retail', account_age_days: 365, is_international: true, timestamp: '2026-03-20T13:10:00Z',
    },
  },
  {
    id: 'S07_new_account_high_risk_merchant',
    name: 'S07: New account + high-risk merchant',
    description: 'Combined medium signals expected REVIEW.',
    suite: 'isolated',
    expected: {
      decision: 'REVIEW',
      scoreMin: 0.4,
      scoreMax: 0.79,
      mustIncludeReasons: ['new_account', 'high_risk_merchant'],
      allowExtraReasons: false,
    },
    category: 'REVIEW',
    payload: {
      transaction_id: 'tx-s07', user_id: 'user-007', amount: 120.0, currency: 'USD', country: 'US', ip_address: '203.0.113.16', device_id: 'device-007', merchant_id: 'merchant-007', merchant_category: 'crypto', account_age_days: 5, is_international: false, timestamp: '2026-03-20T13:20:00Z',
    },
  },
  {
    id: 'S08_high_amount_unusual_hour',
    name: 'S08: High amount + unusual hour',
    description: 'Dual signal combo expected REVIEW.',
    suite: 'isolated',
    expected: {
      decision: 'REVIEW',
      scoreMin: 0.4,
      scoreMax: 0.79,
      mustIncludeReasons: ['high_amount', 'unusual_hour'],
      allowExtraReasons: false,
    },
    category: 'REVIEW',
    payload: {
      transaction_id: 'tx-s08', user_id: 'user-008', amount: 4000.0, currency: 'USD', country: 'US', ip_address: '203.0.113.17', device_id: 'device-008', merchant_id: 'merchant-008', merchant_category: 'retail', account_age_days: 200, is_international: false, timestamp: '2026-03-20T02:40:00Z', transaction_hour: 2,
    },
  },
  {
    id: 'S09_high_amount_high_risk_country',
    name: 'S09: High amount + high-risk country',
    description: 'Strong dual signal expected BLOCK.',
    suite: 'isolated',
    expected: {
      decision: 'BLOCK',
      scoreMin: 0.75,
      scoreMax: 1,
      mustIncludeReasons: ['high_amount', 'high_risk_country'],
      allowExtraReasons: false,
    },
    category: 'BLOCK',
    payload: {
      transaction_id: 'tx-s09', user_id: 'user-009', amount: 5000.0, currency: 'USD', country: 'KP', ip_address: '203.0.113.18', device_id: 'device-009', merchant_id: 'merchant-009', merchant_category: 'retail', account_age_days: 180, is_international: true, timestamp: '2026-03-20T13:40:00Z',
    },
  },
  {
    id: 'S10_multi_rule_severe',
    name: 'S10: Multi-rule severe',
    description: 'High amount + high-risk country + new account + high-risk merchant.',
    suite: 'isolated',
    expected: {
      decision: 'BLOCK',
      scoreMin: 0.75,
      scoreMax: 1,
      mustIncludeReasons: ['high_amount', 'high_risk_country', 'new_account', 'high_risk_merchant', 'unusual_hour'],
      allowExtraReasons: false,
    },
    category: 'BLOCK',
    payload: {
      transaction_id: 'tx-s10', user_id: 'user-010', amount: 1500.0, currency: 'USD', country: 'KP', ip_address: '203.0.113.19', device_id: 'device-010', merchant_id: 'merchant-010', merchant_category: 'crypto', account_age_days: 3, is_international: true, timestamp: '2026-03-20T03:00:00Z', transaction_hour: 3,
    },
  },
  {
    id: 'S11_high_risk_merchant_only',
    name: 'S11: High-risk merchant only',
    description: 'High-risk merchant in isolation.',
    suite: 'isolated',
    expected: {
      decision: 'REVIEW',
      scoreMin: 0.4,
      scoreMax: 0.79,
      mustIncludeReasons: ['high_risk_merchant'],
      allowExtraReasons: false,
    },
    category: 'REVIEW',
    payload: {
      transaction_id: 'tx-s11', user_id: 'user-011', amount: 90.0, currency: 'USD', country: 'US', ip_address: '203.0.113.20', device_id: 'device-011', merchant_id: 'merchant-011', merchant_category: 'crypto', account_age_days: 500, is_international: false, timestamp: '2026-03-20T14:00:00Z',
    },
  },
  {
    id: 'S12_new_account_only',
    name: 'S12: New account only',
    description: 'New account in isolation.',
    suite: 'isolated',
    expected: {
      decision: 'REVIEW',
      scoreMin: 0.4,
      scoreMax: 0.79,
      mustIncludeReasons: ['new_account'],
      allowExtraReasons: false,
    },
    category: 'REVIEW',
    payload: {
      transaction_id: 'tx-s12', user_id: 'user-012', amount: 70.0, currency: 'USD', country: 'US', ip_address: '203.0.113.21', device_id: 'device-012', merchant_id: 'merchant-012', merchant_category: 'retail', account_age_days: 2, is_international: false, timestamp: '2026-03-20T14:10:00Z',
    },
  },
  {
    id: 'S13_international_unusual_round',
    name: 'S13: International + unusual + round',
    description: 'Mixed medium signals expected REVIEW.',
    suite: 'isolated',
    expected: {
      decision: 'REVIEW',
      scoreMin: 0.4,
      scoreMax: 0.79,
      mustIncludeReasons: ['international_transaction', 'unusual_hour', 'round_amount'],
      allowExtraReasons: false,
    },
    category: 'REVIEW',
    payload: {
      transaction_id: 'tx-s13', user_id: 'user-013', amount: 200.0, currency: 'USD', country: 'DE', ip_address: '203.0.113.22', device_id: 'device-013', merchant_id: 'merchant-013', merchant_category: 'retail', account_age_days: 300, is_international: true, timestamp: '2026-03-20T03:25:00Z', transaction_hour: 3,
    },
  },
  {
    id: 'S14_high_amount_high_risk_unusual',
    name: 'S14: High amount + high-risk + unusual',
    description: 'Strong multi-signal expected BLOCK.',
    suite: 'isolated',
    expected: {
      decision: 'BLOCK',
      scoreMin: 0.75,
      scoreMax: 1,
      mustIncludeReasons: ['high_amount', 'high_risk_country', 'unusual_hour'],
      allowExtraReasons: false,
    },
    category: 'BLOCK',
    payload: {
      transaction_id: 'tx-s14', user_id: 'user-014', amount: 7000.0, currency: 'USD', country: 'NG', ip_address: '203.0.113.23', device_id: 'device-014', merchant_id: 'merchant-014', merchant_category: 'retail', account_age_days: 150, is_international: true, timestamp: '2026-03-20T01:10:00Z', transaction_hour: 1,
    },
  },
  {
    id: 'S15_country_new_account_merchant',
    name: 'S15: Country + new account + merchant',
    description: 'High-risk country + new account + high-risk merchant.',
    suite: 'isolated',
    expected: {
      decision: 'BLOCK',
      scoreMin: 0.75,
      scoreMax: 1,
      mustIncludeReasons: ['high_risk_country', 'new_account', 'high_risk_merchant'],
      allowExtraReasons: false,
    },
    category: 'BLOCK',
    payload: {
      transaction_id: 'tx-s15', user_id: 'user-015', amount: 250.0, currency: 'USD', country: 'KP', ip_address: '203.0.113.24', device_id: 'device-015', merchant_id: 'merchant-015', merchant_category: 'crypto', account_age_days: 1, is_international: true, timestamp: '2026-03-20T14:30:00Z',
    },
  },
]

export const statefulScenarios: Scenario[] = [
  {
    id: 'S16_user_velocity_burst',
    name: 'S16: User velocity burst',
    description: '12 tx in short window for same user_id.',
    suite: 'stateful',
    expected: {
      decision: 'REVIEW',
      scoreMin: 0.4,
      scoreMax: 0.95,
      mustIncludeReasons: ['user_velocity'],
      allowExtraReasons: true,
    },
    category: 'Velocity/Graph',
    burstCount: 12,
    burstMode: 'same-user',
    payload: {
      transaction_id: 'tx-s16-1', user_id: 'user-velocity-001', amount: 30.0, currency: 'USD', country: 'US', ip_address: '203.0.113.30', device_id: 'device-030', merchant_id: 'merchant-030', merchant_category: 'retail', account_age_days: 365, is_international: false, timestamp: '2026-03-20T15:00:00Z',
    },
  },
  {
    id: 'S17_ip_velocity_plus_rule',
    name: 'S17: IP velocity + high amount (last)',
    description: '12 tx from same IP with high amount on final transaction.',
    suite: 'stateful',
    expected: {
      decision: 'BLOCK',
      scoreMin: 0.75,
      scoreMax: 1,
      mustIncludeReasons: ['ip_velocity', 'high_amount'],
      allowExtraReasons: true,
    },
    category: 'Velocity/Graph',
    burstCount: 12,
    burstMode: 'same-ip',
    amountSequence: [40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 6000],
    payload: {
      transaction_id: 'tx-s17-1', user_id: 'user-ip-1', amount: 40.0, currency: 'USD', country: 'US', ip_address: '198.51.100.55', device_id: 'device-ip-1', merchant_id: 'merchant-031', merchant_category: 'retail', account_age_days: 365, is_international: false, timestamp: '2026-03-20T15:05:00Z',
    },
  },
  {
    id: 'S18_device_velocity_only',
    name: 'S18: Device velocity only',
    description: '12 tx in short window sharing one device_id.',
    suite: 'stateful',
    expected: {
      decision: 'REVIEW',
      scoreMin: 0.4,
      scoreMax: 0.95,
      mustIncludeReasons: ['device_velocity'],
      allowExtraReasons: true,
    },
    category: 'Velocity/Graph',
    burstCount: 12,
    burstMode: 'same-device',
    payload: {
      transaction_id: 'tx-s18-1', user_id: 'user-device-1', amount: 25.0, currency: 'USD', country: 'US', ip_address: '203.0.113.40', device_id: 'shared-device-001', merchant_id: 'merchant-032', merchant_category: 'retail', account_age_days: 365, is_international: false, timestamp: '2026-03-20T15:10:00Z',
    },
  },
  {
    id: 'S19_shared_device_ring',
    name: 'S19: Shared device ring',
    description: '5+ users on same device to seed graph ring.',
    suite: 'stateful',
    expected: {
      decision: 'REVIEW',
      scoreMin: 0.4,
      scoreMax: 0.95,
      mustIncludeReasons: ['shared_device'],
      allowExtraReasons: true,
    },
    category: 'Velocity/Graph',
    burstCount: 6,
    burstMode: 'same-device',
    payload: {
      transaction_id: 'tx-s19-1', user_id: 'user-ring-1', amount: 55.0, currency: 'USD', country: 'US', ip_address: '203.0.113.60', device_id: 'ring-device-001', merchant_id: 'merchant-033', merchant_category: 'retail', account_age_days: 100, is_international: false, timestamp: '2026-03-20T15:20:00Z',
    },
  },
  {
    id: 'S20_ip_cluster_abuse',
    name: 'S20: IP cluster abuse',
    description: 'Many users from one IP to seed graph IP cluster.',
    suite: 'stateful',
    expected: {
      decision: 'REVIEW',
      scoreMin: 0.4,
      scoreMax: 0.95,
      mustIncludeReasons: ['ip_velocity'],
      allowExtraReasons: true,
    },
    category: 'Velocity/Graph',
    burstCount: 6,
    burstMode: 'same-ip',
    payload: {
      transaction_id: 'tx-s20-1', user_id: 'user-ipcluster-1', amount: 45.0, currency: 'USD', country: 'US', ip_address: '198.51.100.99', device_id: 'device-ipc-1', merchant_id: 'merchant-034', merchant_category: 'retail', account_age_days: 120, is_international: false, timestamp: '2026-03-20T15:30:00Z',
    },
  },
  {
    id: 'S21_merchant_ring_plus_high_amount',
    name: 'S21: Merchant ring + high amount',
    description: 'Distinct users converge on one merchant; final txn high amount.',
    suite: 'stateful',
    expected: {
      decision: 'BLOCK',
      scoreMin: 0.75,
      scoreMax: 1,
      mustIncludeReasons: ['high_amount'],
      allowExtraReasons: true,
    },
    category: 'Velocity/Graph',
    burstCount: 8,
    burstMode: 'same-merchant',
    amountSequence: [80, 80, 80, 80, 80, 80, 80, 6500],
    payload: {
      transaction_id: 'tx-s21-1', user_id: 'user-mring-1', amount: 80.0, currency: 'USD', country: 'US', ip_address: '203.0.113.70', device_id: 'device-mr-1', merchant_id: 'merchant-ring-001', merchant_category: 'retail', account_age_days: 365, is_international: false, timestamp: '2026-03-20T15:40:00Z',
    },
  },
  {
    id: 'S22_country_change_anomaly',
    name: 'S22: Country change anomaly',
    description: 'Txn1 US then Txn2 JP for same user/device in short interval.',
    suite: 'stateful',
    expected: {
      decision: 'REVIEW',
      scoreMin: 0.4,
      scoreMax: 0.95,
      mustIncludeReasons: ['country_change'],
      allowExtraReasons: true,
    },
    category: 'Velocity/Graph',
    burstCount: 2,
    burstMode: 'country-switch',
    countrySequence: ['US', 'JP'],
    payload: {
      transaction_id: 'tx-s22-1', user_id: 'user-travel-001', amount: 30.0, currency: 'USD', country: 'US', ip_address: '203.0.113.80', device_id: 'device-080', merchant_id: 'merchant-035', merchant_category: 'retail', account_age_days: 365, is_international: false, timestamp: '2026-03-20T16:00:00Z',
    },
  },
  {
    id: 'S23_amount_spike_anomaly',
    name: 'S23: Amount spike anomaly',
    description: 'Baseline 20/25 followed by spike 450 for same user.',
    suite: 'stateful',
    expected: {
      decision: 'REVIEW',
      scoreMin: 0.4,
      scoreMax: 0.95,
      mustIncludeReasons: ['amount_spike'],
      allowExtraReasons: true,
    },
    category: 'Velocity/Graph',
    burstCount: 3,
    burstMode: 'amount-spike',
    amountSequence: [20, 25, 450],
    payload: {
      transaction_id: 'tx-s23-1', user_id: 'user-spike-001', amount: 20.0, currency: 'USD', country: 'US', ip_address: '203.0.113.90', device_id: 'device-090', merchant_id: 'merchant-036', merchant_category: 'retail', account_age_days: 365, is_international: false, timestamp: '2026-03-20T16:20:00Z',
    },
  },
]

export const scenarios: Scenario[] = [...isolatedScenarios, ...statefulScenarios]

export const reasonDescriptions: Record<string, string> = {
  high_risk_country: 'Transaction originates from a country flagged as high-risk for fraud',
  elevated_composite_score: 'The combined fraud score from all services exceeds the threshold',
  velocity_spike: 'Unusually high number of transactions in a short time period',
  user_velocity: 'Single user is transacting too frequently in a short time window',
  ip_velocity: 'Many transactions are coming from the same IP address in a short window',
  device_velocity: 'One device is generating unusually frequent transactions',
  country_change: 'Rapid country switching pattern detected for the same user/device',
  amount_spike: 'Current transaction amount spikes above recent spending baseline',
  unusual_amount: 'Transaction amount deviates significantly from user\'s typical spending',
  device_mismatch: 'Device fingerprint does not match any previously seen for this user',
  ip_geo_anomaly: 'IP geolocation does not match the declared transaction country',
  new_account: 'Account was created very recently, increasing fraud risk',
  round_amount: 'Transaction amount is suspiciously round (common in money laundering)',
  high_amount: 'Transaction amount is unusually high',
  international_transaction: 'Cross-border transaction increases risk level',
  high_risk_merchant: 'Merchant category is associated with higher fraud rates',
  multiple_countries: 'Transactions from multiple countries in short timeframe',
  unusual_hour: 'Transaction occurred during an unusual hour compared to normal behavior',
  shared_device: 'Device has been used by multiple different users',
  shared_device_ring: 'Device is shared across multiple users, indicating possible fraud ring behavior',
  ip_cluster: 'IP node is connected to an unusually large suspicious cluster',
  ip_cluster_abuse: 'Many users are linked to the same IP address, indicating potential abuse',
  merchant_ring: 'Merchant is connected to a potentially fraudulent ring pattern',
  velocity_user_exceeded: 'User transaction velocity exceeded configured threshold',
  velocity_ip_exceeded: 'IP transaction velocity exceeded configured threshold',
  velocity_device_exceeded: 'Device transaction velocity exceeded configured threshold',
  new_device_for_user: 'User transacted from a new device not seen in graph history',
  suspicious_ip: 'IP address is associated with known fraudulent activity',
  redis_unavailable: 'Redis was unavailable and velocity checks ran in degraded mode',
  neo4j_unavailable: 'Neo4j was unavailable and graph checks ran in degraded mode',
}

export function generateRandomPayload(): TransactionRequest {
  const countries = ['US', 'GB', 'DE', 'FR', 'JP', 'CA', 'AU', 'BR', 'IN', 'NG']
  const categories = ['retail', 'electronics', 'food_delivery', 'travel', 'gambling', 'crypto_exchange', 'luxury_goods', 'groceries']
  const methods = ['credit_card', 'debit_card', 'digital_wallet', 'bank_transfer', 'crypto']
  const pick = <T>(arr: T[]): T => arr[Math.floor(Math.random() * arr.length)]

  const hour = Math.floor(Math.random() * 24)
  const country = pick(countries)
  const category = pick(categories)

  return {
    transaction_id: `txn_${Math.random().toString(36).slice(2, 14)}`,
    user_id: `user_${Math.random().toString(36).slice(2, 10)}`,
    amount: +(Math.random() * 2000 + 10).toFixed(2),
    merchant_id: `merchant_${category}_${Math.floor(Math.random() * 100) + 1}`,
    currency: 'USD',
    timestamp: new Date().toISOString(),
    country,
    device_id: `dev_${Math.random().toString(36).slice(2, 10)}`,
    ip_address: `${Math.floor(Math.random() * 255)}.${Math.floor(Math.random() * 255)}.${Math.floor(Math.random() * 255)}.${Math.floor(Math.random() * 255)}`,
    merchant_category: category,
    payment_method: pick(methods),
    is_international: country !== 'US',
    customer_age: Math.floor(Math.random() * 60) + 18,
    account_age_days: Math.floor(Math.random() * 3000) + 1,
    transaction_hour: hour,
  }
}
